# This file was generated by GoReleaser. DO NOT EDIT.
cask "base-code" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6393b30884fd5db414c8b1778f32ff6539c358128b42955241b161171e6159fa"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d464c729e6c52727d5b1ac780a2cc65c5edaadf38d0a076c49cc28e1539e3fd"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4c1e23b756fc99f962ca525fa5612200ccf9df83e7b62a8fe3e013c9a99a2ef3"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "73a05d21337378921848e7a190da05c0b09d8422e256d21ad17575740c9bf713"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_linux_arm64.tar.gz"
    end
  end

  name "base-code"
  desc "数据库代码生成器 CLI"
  homepage "https://github.com/dhslegen/base-code"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "base-code"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/base-code"]
    end
  end
  generate_completions_from_executable "base-code",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
