# This file was generated by GoReleaser. DO NOT EDIT.
cask "base-code" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "994be125f593fa28c9e9c590a54015b14c869d20d54df3e949ec46a236eed9b1"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfbe02d20431776b30ad340f6dbe68b49133432f9880b3bf39f46f9c603431a9"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9095eeae25ca32d6d595b78dfd4cfe6a350ac87299e1fe3edc8dd8d9b2ca6bc"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e90e88de0741b7622fa3e85846594ff4c205d98a05413a476ba167a7726ff010"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_linux_arm64.tar.gz"
    end
  end

  name "base-code"
  desc "数据库代码生成器 CLI"
  homepage "https://github.com/dhslegen/base-code"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "base-code"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/base-code"]
    end
  end
  generate_completions_from_executable "base-code",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
