# This file was generated by GoReleaser. DO NOT EDIT.
cask "base-code" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2f20b1ea0f7cb9bd4bd1d5c3971e0e3bd501dd54ac1833544dbea93b64cb21fb"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "283f46574a4247fc0a9570cde61f79d03f643938e9a1ed2575e98d358cdfb3e4"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f2220b318f14a1357b5dd68655644233d8430aeae4e4d08bb79d7f3592dadcec"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2f2665ec9dda404cfe630c6e6eed68afa3da7b619cd80e2061c8ad5db80ba32"
      url "https://github.com/dhslegen/base-code/releases/download/v#{version}/base-code_#{version}_linux_arm64.tar.gz"
    end
  end

  name "base-code"
  desc "数据库代码生成器 CLI"
  homepage "https://github.com/dhslegen/base-code"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "base-code"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/base-code"]
    end
  end
  generate_completions_from_executable "base-code",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
